/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/* This file should be compiled with 6c/8c.  */
#pragma dynimport _ _ "simplelib.so"

#include "runtime.h"
#include "cgocall.h"

#ifdef _64BIT
#define SWIG_PARM_SIZE 8
#else
#define SWIG_PARM_SIZE 4
#endif

#pragma dynimport _wrap_new_StringVector__SWIG_0 _wrap_new_StringVector__SWIG_0 ""
extern void (*_wrap_new_StringVector__SWIG_0)(void*);
static void (*x_wrap_new_StringVector__SWIG_0)(void*) = _wrap_new_StringVector__SWIG_0;

void
·_swig_wrap_new_StringVector__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_StringVector__SWIG_0, &p);
}



#pragma dynimport _wrap_new_StringVector__SWIG_1 _wrap_new_StringVector__SWIG_1 ""
extern void (*_wrap_new_StringVector__SWIG_1)(void*);
static void (*x_wrap_new_StringVector__SWIG_1)(void*) = _wrap_new_StringVector__SWIG_1;

void
·_swig_wrap_new_StringVector__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_StringVector__SWIG_1, &p);
}



#pragma dynimport _wrap_StringVector_size _wrap_StringVector_size ""
extern void (*_wrap_StringVector_size)(void*);
static void (*x_wrap_StringVector_size)(void*) = _wrap_StringVector_size;

void
·_swig_wrap_StringVector_size(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_StringVector_size, &p);
}



#pragma dynimport _wrap_StringVector_capacity _wrap_StringVector_capacity ""
extern void (*_wrap_StringVector_capacity)(void*);
static void (*x_wrap_StringVector_capacity)(void*) = _wrap_StringVector_capacity;

void
·_swig_wrap_StringVector_capacity(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_StringVector_capacity, &p);
}



#pragma dynimport _wrap_StringVector_reserve _wrap_StringVector_reserve ""
extern void (*_wrap_StringVector_reserve)(void*);
static void (*x_wrap_StringVector_reserve)(void*) = _wrap_StringVector_reserve;

void
·_swig_wrap_StringVector_reserve(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_StringVector_reserve, &p);
}



#pragma dynimport _wrap_StringVector_isEmpty _wrap_StringVector_isEmpty ""
extern void (*_wrap_StringVector_isEmpty)(void*);
static void (*x_wrap_StringVector_isEmpty)(void*) = _wrap_StringVector_isEmpty;

void
·_swig_wrap_StringVector_isEmpty(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_StringVector_isEmpty, &p);
}



#pragma dynimport _wrap_StringVector_clear _wrap_StringVector_clear ""
extern void (*_wrap_StringVector_clear)(void*);
static void (*x_wrap_StringVector_clear)(void*) = _wrap_StringVector_clear;

void
·_swig_wrap_StringVector_clear(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_StringVector_clear, &p);
}



#pragma dynimport _wrap_StringVector_add _wrap_StringVector_add ""
extern void (*_wrap_StringVector_add)(void*);
static void (*x_wrap_StringVector_add)(void*) = _wrap_StringVector_add;

void
·_swig_wrap_StringVector_add(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_StringVector_add, &p);
}



#pragma dynimport _wrap_StringVector_get _wrap_StringVector_get ""
extern void (*_wrap_StringVector_get)(void*);
static void (*x_wrap_StringVector_get)(void*) = _wrap_StringVector_get;

void
·_swig_wrap_StringVector_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_StringVector_get, &p);
}



#pragma dynimport _wrap_StringVector_set _wrap_StringVector_set ""
extern void (*_wrap_StringVector_set)(void*);
static void (*x_wrap_StringVector_set)(void*) = _wrap_StringVector_set;

void
·_swig_wrap_StringVector_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_StringVector_set, &p);
}



#pragma dynimport _wrap_delete_StringVector _wrap_delete_StringVector ""
extern void (*_wrap_delete_StringVector)(void*);
static void (*x_wrap_delete_StringVector)(void*) = _wrap_delete_StringVector;

void
·_swig_wrap_delete_StringVector(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_StringVector, &p);
}



#pragma dynimport _wrap_new_ByteVector__SWIG_0 _wrap_new_ByteVector__SWIG_0 ""
extern void (*_wrap_new_ByteVector__SWIG_0)(void*);
static void (*x_wrap_new_ByteVector__SWIG_0)(void*) = _wrap_new_ByteVector__SWIG_0;

void
·_swig_wrap_new_ByteVector__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_ByteVector__SWIG_0, &p);
}



#pragma dynimport _wrap_new_ByteVector__SWIG_1 _wrap_new_ByteVector__SWIG_1 ""
extern void (*_wrap_new_ByteVector__SWIG_1)(void*);
static void (*x_wrap_new_ByteVector__SWIG_1)(void*) = _wrap_new_ByteVector__SWIG_1;

void
·_swig_wrap_new_ByteVector__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_ByteVector__SWIG_1, &p);
}



#pragma dynimport _wrap_ByteVector_size _wrap_ByteVector_size ""
extern void (*_wrap_ByteVector_size)(void*);
static void (*x_wrap_ByteVector_size)(void*) = _wrap_ByteVector_size;

void
·_swig_wrap_ByteVector_size(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ByteVector_size, &p);
}



#pragma dynimport _wrap_ByteVector_capacity _wrap_ByteVector_capacity ""
extern void (*_wrap_ByteVector_capacity)(void*);
static void (*x_wrap_ByteVector_capacity)(void*) = _wrap_ByteVector_capacity;

void
·_swig_wrap_ByteVector_capacity(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ByteVector_capacity, &p);
}



#pragma dynimport _wrap_ByteVector_reserve _wrap_ByteVector_reserve ""
extern void (*_wrap_ByteVector_reserve)(void*);
static void (*x_wrap_ByteVector_reserve)(void*) = _wrap_ByteVector_reserve;

void
·_swig_wrap_ByteVector_reserve(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ByteVector_reserve, &p);
}



#pragma dynimport _wrap_ByteVector_isEmpty _wrap_ByteVector_isEmpty ""
extern void (*_wrap_ByteVector_isEmpty)(void*);
static void (*x_wrap_ByteVector_isEmpty)(void*) = _wrap_ByteVector_isEmpty;

void
·_swig_wrap_ByteVector_isEmpty(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ByteVector_isEmpty, &p);
}



#pragma dynimport _wrap_ByteVector_clear _wrap_ByteVector_clear ""
extern void (*_wrap_ByteVector_clear)(void*);
static void (*x_wrap_ByteVector_clear)(void*) = _wrap_ByteVector_clear;

void
·_swig_wrap_ByteVector_clear(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ByteVector_clear, &p);
}



#pragma dynimport _wrap_ByteVector_add _wrap_ByteVector_add ""
extern void (*_wrap_ByteVector_add)(void*);
static void (*x_wrap_ByteVector_add)(void*) = _wrap_ByteVector_add;

void
·_swig_wrap_ByteVector_add(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ByteVector_add, &p);
}



#pragma dynimport _wrap_ByteVector_get _wrap_ByteVector_get ""
extern void (*_wrap_ByteVector_get)(void*);
static void (*x_wrap_ByteVector_get)(void*) = _wrap_ByteVector_get;

void
·_swig_wrap_ByteVector_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ByteVector_get, &p);
}



#pragma dynimport _wrap_ByteVector_set _wrap_ByteVector_set ""
extern void (*_wrap_ByteVector_set)(void*);
static void (*x_wrap_ByteVector_set)(void*) = _wrap_ByteVector_set;

void
·_swig_wrap_ByteVector_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ByteVector_set, &p);
}



#pragma dynimport _wrap_delete_ByteVector _wrap_delete_ByteVector ""
extern void (*_wrap_delete_ByteVector)(void*);
static void (*x_wrap_delete_ByteVector)(void*) = _wrap_delete_ByteVector;

void
·_swig_wrap_delete_ByteVector(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_ByteVector, &p);
}



#pragma dynimport _wrap_new_SimpleClass _wrap_new_SimpleClass ""
extern void (*_wrap_new_SimpleClass)(void*);
static void (*x_wrap_new_SimpleClass)(void*) = _wrap_new_SimpleClass;

void
·_swig_wrap_new_SimpleClass(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_SimpleClass, &p);
}



#pragma dynimport _wrap_SimpleClass_hello__SWIG_0 _wrap_SimpleClass_hello__SWIG_0 ""
extern void (*_wrap_SimpleClass_hello__SWIG_0)(void*);
static void (*x_wrap_SimpleClass_hello__SWIG_0)(void*) = _wrap_SimpleClass_hello__SWIG_0;

void
·_swig_wrap_SimpleClass_hello__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_SimpleClass_hello__SWIG_0, &p);
}



#pragma dynimport _wrap_SimpleClass_hello__SWIG_1 _wrap_SimpleClass_hello__SWIG_1 ""
extern void (*_wrap_SimpleClass_hello__SWIG_1)(void*);
static void (*x_wrap_SimpleClass_hello__SWIG_1)(void*) = _wrap_SimpleClass_hello__SWIG_1;

void
·_swig_wrap_SimpleClass_hello__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_SimpleClass_hello__SWIG_1, &p);
}



#pragma dynimport _wrap_SimpleClass_hello__SWIG_2 _wrap_SimpleClass_hello__SWIG_2 ""
extern void (*_wrap_SimpleClass_hello__SWIG_2)(void*);
static void (*x_wrap_SimpleClass_hello__SWIG_2)(void*) = _wrap_SimpleClass_hello__SWIG_2;

void
·_swig_wrap_SimpleClass_hello__SWIG_2(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_SimpleClass_hello__SWIG_2, &p);
}



#pragma dynimport _wrap_delete_SimpleClass _wrap_delete_SimpleClass ""
extern void (*_wrap_delete_SimpleClass)(void*);
static void (*x_wrap_delete_SimpleClass)(void*) = _wrap_delete_SimpleClass;

void
·_swig_wrap_delete_SimpleClass(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_SimpleClass, &p);
}



